### PR TITLE
Change license field to reflect structuredLicense.url or default to empty string

### PR DESCRIPTION
**Pull request by sonofflynn89**
See https://devtopia.esri.com/dc/hub/issues/1418

### CODE REVIEW

**Review by andrewctate — COMMENTED** [review]
One request: we're trying to move toward marking properties as `null` when they're unavailable. Could we use `null` instead of the empty string?

**Comment by sonofflynn89** [comment]
I have no problem as long as Thomas is ok with it! He specifically asked for the empty string in the issue, but I'm sure he'll be fine with null.

**Comment by sonofflynn89** [comment]
@andrewctate Thomas approved and `''` has been changed to `null`.

**Review by andrewctate — APPROVED** [review]
Nice work!

**Pull request merged**
